config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  resources "search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    if params.has_key?(:imei)

      result = {}
      @bingo = false

      location = params[:imei][0]
      case location
      when 'C'
        result[:location] = "深圳"
      when 'D'
        result[:location] = "成都"
      when 'F'
        result[:location] = "鄭州"
      end

      year = params[:imei][3]
      case year
      when 'P'
        result[:year] = "2015年上半年"
      when 'Q'
        result[:year] = "2015年下半年"
      when 'R'
        result[:year] = "2016年上半年"
      when 'S'
        result[:year] = "2016年下半年"
      end

      week = params[:imei][4]
      case week
      when '1'
        result[:week] = ['0701','0707']
      when '2'
        result[:week] = ['0708','0714']
      when '3'
        result[:week] = ['0715','0721']
      when '4'
        result[:week] = ['0722','0728']
      when '5'
        result[:week] = ['0729','0804']
      when '6'
        result[:week] = ['0805','0811']
      when '7'
        result[:week] = ['0812','0818']
      when '8'
        result[:week] = ['0819','0825']
      when '9'
        result[:week] = ['0826','0901']
        @bingo = true
      when 'C'
        result[:week] = ['0902','0908']
        @bingo = true
      when 'D'
        result[:week] = ['0909','0915']
        @bingo = true
      when 'F'
        result[:week] = ['0916','0922']
        @bingo = true
      when 'G'
        result[:week] = ['0923','0929']
        @bingo = true
      when 'H'
        result[:week] = ['0930','1006']
        @bingo = true
      when 'J'
        result[:week] = ['1007','1013']
        @bingo = true
      when 'K'
        result[:week] = ['1014','1020']
        @bingo = true
      when 'L'
        result[:week] = ['1021','1027']
        @bingo = true
      when 'M'
        result[:week] = ['1028','1103']
        @bingo = true
      when 'N'
        result[:week] = ['1104','1110']
      when 'P'
        result[:week] = ['1111','1117']
      when 'Q'
        result[:week] = ['1118','1124']
      when 'R'
        result[:week] = ['1125','1201']
      when 'T'
        result[:week] = ['1202','1208']
      when 'V'
        result[:week] = ['1209','1215']
      when 'W'
        result[:week] = ['1216','1222']
      when 'X'
        result[:week] = ['1223','1229']
      when 'Y'
        result[:week] = ['1230','1231']
      end

      @location = result[:location]

      if year == "Q" and @bingo = true
        @bingo = true
      else
        @bingo = false
      end

      if year == "P" or year == "R"
        @day_begin = result[:year][0..3] + "上半年"
        @day_end = ""
      else
        @day_begin = Date.parse(result[:year][0..3] + result[:week][0])
        @day_end = Date.parse(result[:year][0..3] + result[:week][1])
      end

    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_footer.html.erb
<footer class="text-center">
  <div class="footer-below">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="fb-like" data-href="https://iphone6s-check-mfg.herokuapp.com/" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
          <div class="col-md-12" style="padding: 10px;">
            Copyright © <a href="https://github.com/niclin">NicLin</a> 2016
          </div>
        </div>
      </div>
    </div>
  </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IphoneCheckMfg</title>

    <meta property="og:title" content='Iphone生產日期及產地檢查器'/>
    <meta property="og:image" content='http://i.imgur.com/VtMZWvB.png'/>
    <meta property="og:description" content="檢查你的Iphone6S是否符合電池更換計畫"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= render 'common/footer'%>
    <div id="fb-root"></div>
  </body>


<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/zh_TW/sdk.js#xfbml=1&version=v2.8&appId=1803103906624892";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-45192107-5', 'auto');
  ga('send', 'pageview');
  </script>

</html>

app/views/search/index.html.erb
<section class="result-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="iphone">
          <%= image_tag 'iphone.png', class: 'img-responsive'%>
        </div>
      </div>
      <div class="col-md-6">
        <table class="table table-striped">
          <thead>
            <tr>
              <th style="width: 30%">製造地點</th>
              <th>生產時間</th>
              <th>召修方案</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <%= @location %>
              </td>
              <td>
                <%= @day_begin %>～<%= @day_end%>
              </td>
              <td>
                <% if @bingo %>
                <a href="https://www.apple.com/tw/support/iphone6s-unexpectedshutdown/">符合Iphone6s電池召修方案</a>
                <% else %>
                無符合召修方案
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
        <%= link_to '繼續查詢', root_path, class: 'btn btn-primary pull-right' %>
      </div>
    </div>
  </div>
  <br>
</section>

app/views/welcome/index.html.erb
<section class="search-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-centered">
                <%= form_tag(search_index_path, method: :get) do %>
                <h2 class="imei-input text-center">檢查您的手機生產日期及產地</h2>
                <h3 class="imei-input text-center">立刻輸入你的Iphone序號</h3>
                <hr class="light">
                <div id="custom-search-input">
                    <div class="input-group col-md-12">
                        <input type="text" name="imei" class="form-control input-lg" placeholder="ex:DNPQ3R4FGRYD" />
                        <span class="input-group-btn">
                            <button class="btn btn-default btn-lg" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                            </button>
                        </span>
                    </div>
                    <h4 class="imei-input text-center">設定->一般->關於本機->序號</h4>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>
</section>